In [17]:
import pandas as pd
data= pd.read_csv('Housing.csv')
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [18]:
data.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [36]:
data.mainroad.value_counts()
# # data.guestroom.value_counts()
# # data.basement.value_counts()
# # data.hotwaterheating.value_counts()
# # data.prefarea.value_counts()
# data.furnishingstatus.value_counts()
#

mainroad
1    468
0     77
Name: count, dtype: int64

In [20]:
data.mainroad= data.mainroad.map({'yes':1,'no':0})
data.guestroom= data.guestroom.map({'yes':1,'no':0})
data.basement= data.basement.map({'yes':1,'no':0})
data.hotwaterheating= data.hotwaterheating.map({'yes':1,'no':0})
data.airconditioning= data.airconditioning.map({'yes':1,'no':0})
data.prefarea= data.prefarea.map({'yes':1,'no':0})

In [21]:
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,furnished
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,furnished
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,semi-furnished
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,furnished
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,unfurnished
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,semi-furnished
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,unfurnished
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,furnished
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,unfurnished

In [24]:
from sklearn.preprocessing import LabelEncoder
encoder= LabelEncoder()
data.loc[:,'furnishingstatus']= encoder.fit_transform(data.loc[:,'furnishingstatus'])

In [25]:
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,2
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,1
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,2
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,0
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,2

In [26]:
data.loc[:,'furnishingstatus'].value_counts()

furnishingstatus
1    227
2    178
0    140
Name: count, dtype: int64

In [27]:
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0

In [30]:
# independent or dependent variables 
x= data.iloc[:,1:]
y=data.loc[:,'price']
y

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.3, random_state=10)

In [33]:
x_train

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
175,9800,4,2,2,1,1,0,0,0,2,0,1
25,6540,4,2,2,1,1,1,0,1,2,1,0
253,3520,2,1,2,1,0,0,0,0,0,1,0
257,8250,3,1,1,1,0,0,0,0,0,0,0
431,3180,4,1,2,1,0,1,0,1,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
369,3600,2,1,1,1,0,0,0,0,0,0,0
320,4320,3,1,2,1,0,0,0,0,2,1,0
527,1836,2,1,1,0,0,1,0,0,0,0,1
125,15600,3,1,1,1,0,0,0,1,2,0,1
265,2880,3,1,2,1,0,0,0,0,0,1,1

In [34]:
y_train

175    5250000
25     8540000
253    4515000
257    4480000
431    3290000
        ...
369    3675000
320    4060000
527    2275000
125    5943000
265    4403000
Name: price, Length: 381, dtype: int64

In [37]:
from sklearn.linear_model import LinearRegression 
model= LinearRegression()

In [38]:
model.fit(x_train,y_train)

LinearRegression()

In [39]:
y_pred= model.predict(x_test)

In [41]:
# y_pred

In [42]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.742384108045443

In [43]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_pred)
print("MSE:", mse)

MSE: 751121857487.2772

In [44]:
import joblib
joblib.dump(model,'house.pkl')

['house.pkl']

In [45]:
data.to_csv('converted.csv')

In [47]:
import joblib
house =joblib.load('house.pkl')
house.predict([[9960,4,2,3,1,0,1,0,1,2,1,0]])

c:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([9403962.03642794])

In [52]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("yasserh/housing-prices-dataset")
path
# print("Path to dataset files:", path)

'C:\\Users\\hp\\.cache\\kagglehub\\datasets\\yasserh\\housing-prices-dataset\\versions\\1'

In [49]:
!pip install kagglehub

Collecting kagglehub
  Downloading kagglehub-1.0.0-py3-none-any.whl.metadata (40 kB)
     ---------------------------------------- 0.0/40.1 kB ? eta -:--:--
     ---------------------------------------- 40.1/40.1 kB 2.0 MB/s eta 0:00:00
Collecting kagglesdk<1.0,>=0.1.14 (from kagglehub)
  Downloading kagglesdk-0.1.15-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from kagglehub) (23.2)
Requirement already satisfied: pyyaml in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from kagglehub) (6.0.1)
Requirement already satisfied: requests in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from kagglehub) (4.66.4)
Requirement already satisfied: protobuf in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (4.25.8)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from requests->kagglehub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from requests->kagglehub) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from requests->kagglehub) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from requests->kagglehub) (2024.6.2)
Requirement already satisfied: colorama in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-1.0.0-py3-none-any.whl (70 kB)
   ---------------------------------------- 0.0/70.6 kB ? eta -:--:--
   ---------------------------------------- 70.6/70.6 kB 4.0 MB/s eta 0:00:00
Downloading kagglesdk-0.1.15-py3-none-any.whl (160 kB)
   ---------------------------------------- 0.0/160.4 kB ? eta -:--:--
   ---------------------------------------- 160.4/160.4 kB 4.8 MB/s eta 0:00:00
Installing collected packages: kagglesdk, kagglehub
Successfully installed kagglehub-1.0.0 kagglesdk-0.1.15

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip