In [1]:
import pandas as pd

In [2]:
# dataframes - 2d shape 
df= pd.read_csv("pre-owned cars.csv")

In [3]:
df.head()

,brand,model,transmission,make_year,reg_year,fuel_type,engine_capacity(CC),km_driven,ownership,price,overall_cost,has_insurance,spare_key,reg_number,title
0,Mahindra,Thar LX D 4WD MT CONVERTIBLE,Manual,2020.0,01-01-2021,Diesel,2184.0,11003.0,1st owner,1231000,23431.0,True,No,HR26,2020 Mahindra Thar LX D 4WD MT CONVERTIBLE
1,Hyundai,Verna 1.6 VTVT SX,Manual,2018.0,01-07-2018,Petrol,1591.0,66936.0,1st owner,786000,15359.0,True,No,DL7C,2018 Hyundai Verna 1.6 VTVT SX
2,Tata,Harrier XT PLUS 2.0L KRYOTEC DARK EDITON,Manual,2022.0,01-08-2022,Diesel,1956.0,27990.0,1st owner,1489000,28349.0,True,No,HR29,2022 Tata Harrier XT PLUS 2.0L KRYOTEC DARK ED...
3,Honda,City 1.5L I-VTE V CVT,Automatic,2023.0,01-04-2023,Petrol,1498.0,5061.0,1st owner,1227000,23355.0,True,Yes,DL4C,2023 Honda City 1.5L I-VTE V CVT
4,Ford,Ecosport TITANIUM 1.5L DIESEL,Manual,2021.0,01-07-2021,Diesel,1498.0,23480.0,1st owner,887000,16883.0,True,No,UP14,2021 Ford Ecosport TITANIUM 1.5L DIESEL

In [4]:
df.shape

(2806, 15)

In [5]:
df.columns

Index(['brand', 'model', 'transmission', 'make_year', 'reg_year', 'fuel_type',
       'engine_capacity(CC)', 'km_driven', 'ownership', 'price',
       'overall_cost', 'has_insurance', 'spare_key', 'reg_number', 'title'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2806 entries, 0 to 2805
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   brand                2805 non-null   object
 1   model                2805 non-null   object
 2   transmission         2805 non-null   object
 3   make_year            2805 non-null   float64
 4   reg_year             720 non-null    object
 5   fuel_type            2805 non-null   object
 6   engine_capacity(CC)  2688 non-null   float64
 7   km_driven            2805 non-null   float64
 8   ownership            2805 non-null   object
 9   price                2806 non-null   int64
 10  overall_cost         2805 non-null   float64
 11  has_insurance        2805 non-null   object
 12  spare_key            2805 non-null   object
 13  reg_number           2805 non-null   object
 14  title                2805 non-null   object
dtypes: float64(4), int64(1), object(10)
memory usage: 329.0+ KB

In [7]:
df.describe()

,make_year,engine_capacity(CC),km_driven,price,overall_cost
count,2805.000000,2688.000000,2805.000000,2.806000e+03,2805.000000
mean,2018.181105,1259.027530,49215.477362,1.342522e+06,13495.022816
std,2.945293,254.504798,26626.932696,3.554669e+07,6040.809220
min,2010.000000,624.000000,450.000000,1.630000e+05,4039.000000
25%,2016.000000,1194.000000,28540.000000,4.350000e+05,9267.000000
50%,2018.000000,1197.000000,45695.000000,5.940000e+05,12145.000000
75%,2021.000000,1462.000000,68182.000000,8.140000e+05,15760.000000
max,2024.000000,2694.000000,143991.000000,1.883558e+09,47338.000000

In [11]:
df.loc[:,'transmission'].value_counts()

transmission
Manual       1925
Automatic     880
Name: count, dtype: int64

In [13]:
df[df.loc[:,'transmission']=='Automatic']

,brand,model,transmission,make_year,reg_year,fuel_type,engine_capacity(CC),km_driven,ownership,price,overall_cost,has_insurance,spare_key,reg_number,title
3,Honda,City 1.5L I-VTE V CVT,Automatic,2023.0,01-04-2023,Petrol,1498.0,5061.0,1st owner,1227000,23355.0,True,Yes,DL4C,2023 Honda City 1.5L I-VTE V CVT
7,Tata,NEXON XMA DIESEL,Automatic,2020.0,01-02-2021,Diesel,NaN,59866.0,1st owner,728000,14228.0,True,No,DL5C,2020 Tata NEXON XMA DIESEL
8,Mahindra,XUV700 AX 7 LUXURY D AWD AT 7 STR,Automatic,2022.0,01-04-2022,Diesel,2184.0,62567.0,1st owner,2322000,44197.0,True,No,DL10,2022 Mahindra XUV700 AX 7 LUXURY D AWD AT 7 STR
9,Ford,Ecosport TITANIUM + 1.5L PETROL AT,Automatic,2019.0,01-07-2019,Petrol,1497.0,58503.0,1st owner,766000,14977.0,True,No,DL10,2019 Ford Ecosport TITANIUM + 1.5L PETROL AT
16,Maruti,Alto K10 VXI AMT,Automatic,2014.0,01-02-2015,Petrol,998.0,71297.0,1st owner,265000,5901.0,True,No,DL3C,2014 Maruti Alto K10 VXI AMT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2795,Tata,NEXON FEARLESS + SUNROOF DCA DUAL TONE 1.2 PETROL,Automatic,2024.0,NaN,Petrol,NaN,11540.0,1st owner,1399000,26629.0,True,Yes,MH46,2024 Tata NEXON FEARLESS + SUNROOF DCA DUAL TO...
2797,Hyundai,NEW I20 ASTA 1.2 AT,Automatic,2021.0,NaN,Petrol,1197.0,15831.0,1st owner,831000,15817.0,True,Yes,MH05,2021 Hyundai NEW I20 ASTA 1.2 AT
2798,Hyundai,NEW SANTRO SPORTZ AMT,Automatic,2019.0,NaN,Petrol,1086.0,56370.0,2nd owner,396000,7732.0,True,Yes,MH48,2019 Hyundai NEW SANTRO SPORTZ AMT
2799,Maruti,IGNIS DELTA 1.2 AMT,Automatic,2017.0,NaN,Petrol,1197.0,80035.0,1st owner,428000,8377.0,True,No,MH01,2017 Maruti IGNIS DELTA 1.2 AMT
2801,Ford,Ecosport TREND + 1.5L PETROL AT,Automatic,2018.0,NaN,Petrol,1497.0,46982.0,1st owner,661000,12920.0,True,Yes,MH03,2018 Ford Ecosport TREND + 1.5L PETROL AT

In [14]:
df[(df.loc[:,'transmission']=='Automatic') & (df.loc[:,'fuel_type']=='Electric')]

,brand,model,transmission,make_year,reg_year,fuel_type,engine_capacity(CC),km_driven,ownership,price,overall_cost,has_insurance,spare_key,reg_number,title
394,Tata,NEXON EV XZ PLUS,Automatic,2020.0,01-11-2020,Electric,NaN,46001.0,1st owner,1100000,20937.0,True,Yes,DL12,2020 Tata NEXON EV XZ PLUS
573,Tata,TIAGO EV XT LONG RANGE,Automatic,2023.0,01-12-2023,Electric,NaN,10423.0,1st owner,875000,16655.0,True,No,UP16,2023 Tata TIAGO EV XT LONG RANGE
623,Tata,NEXON EV XZ PLUS,Automatic,2022.0,01-03-2022,Electric,NaN,56728.0,1st owner,1350000,25696.0,True,Yes,DL7G,2022 Tata NEXON EV XZ PLUS
672,Tata,NEXON EV XM,Automatic,2023.0,01-08-2023,Electric,NaN,40647.0,1st owner,1411000,26857.0,True,Yes,UP16,2023 Tata NEXON EV XM

In [17]:
df.isnull().sum()

brand                     1
model                     1
transmission              1
make_year                 1
reg_year               2086
fuel_type                 1
engine_capacity(CC)     118
km_driven                 1
ownership                 1
price                     0
overall_cost              1
has_insurance             1
spare_key                 1
reg_number                1
title                     1
dtype: int64

In [18]:
df.dropna(axis=1)  # axis=0, axis=1

           price
0        1231000
1         786000
2        1489000
3        1227000
4         887000
...          ...
2801      661000
2802      412000
2803      496000
2804      509000
2805  1883558000

[2806 rows x 1 columns]

In [21]:
df.drop('reg_year', axis=1, inplace=True)

In [22]:
df.shape

(2806, 14)

In [23]:
df.dropna(axis=0, inplace=True)
df.shape

(2688, 14)

In [24]:
df.isnull().sum()

brand                  0
model                  0
transmission           0
make_year              0
fuel_type              0
engine_capacity(CC)    0
km_driven              0
ownership              0
price                  0
overall_cost           0
has_insurance          0
spare_key              0
reg_number             0
title                  0
dtype: int64

In [25]:
df.to_csv('new.csv')