In [63]:
import pandas as pd
# df= pd.read_excel('')
df=pd.read_csv('Titanic-Dataset.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [64]:
df.shape

(891, 12)

In [65]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [67]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [68]:
df.drop('Cabin', inplace=True, axis=1)  # axis=1 column, axis=0 row

In [69]:
df.shape

(891, 11)

In [70]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         2
dtype: int64

In [71]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [72]:
df.Age.min()

0.42

In [73]:
df.Age.max()

80.0

In [74]:
df.Age.mean()

29.69911764705882

In [75]:
df.Name[:10]

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
5                                     Moran, Mr. James
6                              McCarthy, Mr. Timothy J
7                       Palsson, Master. Gosta Leonard
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                  Nasser, Mrs. Nicholas (Adele Achem)
Name: Name, dtype: object

In [84]:
new= df.Name.str.split(',').str[1].str.split('.').str[0].str.strip()
new

0        Mr
1       Mrs
2      Miss
3       Mrs
4        Mr
       ...
886     Rev
887    Miss
888    Miss
889      Mr
890      Mr
Name: Name, Length: 891, dtype: object

In [85]:
new

0        Mr
1       Mrs
2      Miss
3       Mrs
4        Mr
       ...
886     Rev
887    Miss
888    Miss
889      Mr
890      Mr
Name: Name, Length: 891, dtype: object

In [86]:
df.insert(6,column='start',value=new)

In [87]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,start,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,Mr,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,Mrs,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,Miss,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,Mrs,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,Mr,0,0,373450,8.0500,S

In [88]:
mr_df= df[df.loc[:,'start']=='Mr']

In [89]:
mr_df

,PassengerId,Survived,Pclass,Name,Sex,Age,start,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,Mr,1,0,A/5 21171,7.2500,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,Mr,0,0,373450,8.0500,S
5,6,0,3,"Moran, Mr. James",male,NaN,Mr,0,0,330877,8.4583,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,Mr,0,0,17463,51.8625,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,Mr,0,0,A/5. 2151,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...,...
881,882,0,3,"Markun, Mr. Johann",male,33.0,Mr,0,0,349257,7.8958,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,Mr,0,0,C.A./SOTON 34068,10.5000,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,Mr,0,0,SOTON/OQ 392076,7.0500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,Mr,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,Mr,0,0,370376,7.7500,Q

In [90]:
mr_age_mean= mr_df.Age.mean()

In [91]:
mr_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            119
start            0
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         0
dtype: int64

In [100]:
mr_df[mr_df.Age.isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,start,SibSp,Parch,Ticket,Fare,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,Mr,0,0,330877,8.4583,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,Mr,0,0,244373,13.0000,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,Mr,0,0,2631,7.2250,C
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,Mr,0,0,349216,7.8958,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,Mr,0,0,2677,7.2292,C
...,...,...,...,...,...,...,...,...,...,...,...,...
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,Mr,0,0,11774,29.7000,C
846,847,0,3,"Sage, Mr. Douglas Bullen",male,NaN,Mr,8,2,CA. 2343,69.5500,S
859,860,0,3,"Razi, Mr. Raihed",male,NaN,Mr,0,0,2629,7.2292,C
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,Mr,0,0,345777,9.5000,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,Mr,0,0,349217,7.8958,S

In [93]:
mr_index = mr_df[mr_df.Age.isnull()].index

In [94]:
mr_index

Index([  5,  17,  26,  29,  36,  42,  45,  46,  48,  55,
       ...
       825, 826, 828, 832, 837, 839, 846, 859, 868, 878],
      dtype='int64', length=119)

In [95]:
df.loc[mr_index,'Age']=mr_age_mean

In [96]:
df.isnull().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
Sex             0
Age            58
start           0
SibSp           0
Parch           0
Ticket          0
Fare            0
Embarked        2
dtype: int64

In [49]:
# df.loc[mr_index,:]

In [50]:
mrs_df= df[df.loc[:,'start']=='Mrs']

In [52]:
mrs_df.isnull().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
Sex             0
Age            17
start           0
SibSp           0
Parch           0
Ticket          0
Fare            0
Embarked        1
dtype: int64

In [53]:
mrs_age_mean= mrs_df.Age.mean()

In [54]:
mrs_age_mean

35.898148148148145

In [58]:
mrs_index = mrs_df[mrs_df.Age.isnull()].index

In [59]:
mrs_index

Index([ 19,  31, 140, 166, 186, 256, 334, 347, 367, 375, 415, 431, 457, 533,
       578, 669, 849],
      dtype='int64')

In [60]:
df.loc[mrs_index,'Age']= mrs_age_mean

In [61]:
df.loc[mrs_index,:]

,PassengerId,Survived,Pclass,Name,Sex,Age,start,SibSp,Parch,Ticket,Fare,Embarked
19,20,1,3,"Masselmani, Mrs. Fatima",female,35.898148,Mrs,0,0,2649,7.2250,C
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,35.898148,Mrs,1,0,PC 17569,146.5208,C
140,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,35.898148,Mrs,0,2,2678,15.2458,C
166,167,1,1,"Chibnall, Mrs. (Edith Martha Bowerman)",female,35.898148,Mrs,0,1,113505,55.0000,S
186,187,1,3,"O'Brien, Mrs. Thomas (Johanna ""Hannah"" Godfrey)",female,35.898148,Mrs,1,0,370365,15.5000,Q
256,257,1,1,"Thorne, Mrs. Gertrude Maybelle",female,35.898148,Mrs,0,0,PC 17585,79.2000,C
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,35.898148,Mrs,1,0,PC 17611,133.6500,S
347,348,1,3,"Davison, Mrs. Thomas Henry (Mary E Finck)",female,35.898148,Mrs,1,0,386525,16.1000,S
367,368,1,3,"Moussa, Mrs. (Mantoura Boulos)",female,35.898148,Mrs,0,0,2626,7.2292,C
375,376,1,1,"Meyer, Mrs. Edgar Joseph (Leila Saks)",female,35.898148,Mrs,1,0,PC 17604,82.1708,C
415,416,0,3,"Meek, Mrs. Thomas (Annie Louise Rowley)",female,35.898148,Mrs,0,0,343095,8.0500,S
431,432,1,3,"Thorneycroft, Mrs. Percival (Florence Kate White)",female,35.898148,Mrs,1,0,376564,16.1000,S
457,458,1,1,"Kenyon, Mrs. Frederick R (Marion)",female,35.898148,Mrs,1,0,17464,51.8625,S
533,534,1,3,"Peter, Mrs. Catherine (Catherine Rizk)",female,35.898148,Mrs,0,2,2668,22.3583,C
578,579,0,3,"Caram, Mrs. Joseph (Maria Elias)",female,35.898148,Mrs,1,0,2689,14.4583,C
669,670,1,1,"Taylor, Mrs. Elmer Zebley (Juliet Cummins Wright)",female,35.898148,Mrs,1,0,19996,52.0000,S
849,850,1,1,"Goldenberg, Mrs. Samuel L (Edwiga Grabowska)",female,35.898148,Mrs,1,0,17453,89.1042,C

In [62]:
df.isnull().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
Sex             0
Age            41
start           0
SibSp           0
Parch           0
Ticket          0
Fare            0
Embarked        2
dtype: int64